package message.providers;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Map;

@SpringBootTest
public class JsonWebTokenProviderTest {

    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void test() {
        Map<String, String> decoder = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkFka3p3Q1IyVUNYckllZnplRnZCMiJ9.eyJnaXZlbl9uYW1lIjoiQWJtYWVsIiwiZmFtaWx5X25hbWUiOiJGZXJyZWlyYSIsIm5pY2tuYW1lIjoiYWJtYWVsLm5pbmhhIiwibmFtZSI6IkFibWFlbCBGZXJyZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKbndLbld5QzJEQXpydWFWeWxBSDdZUG12U3pfam51OUFrU202Ty0tbDF6X3Nmcnhpdj1zOTYtYyIsInVwZGF0ZWRfYXQiOiIyMDI2LTAxLTA0VDIxOjA3OjQ4LjE1M1oiLCJlbWFpbCI6ImFibWFlbC5uaW5oYUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kZXYtbnVycDcwOGRscGhoMWF0eC51cy5hdXRoMC5jb20vIiwiYXVkIjoidXRuaWhGU21IM3drSk1RRXRZeUdjTmxYNkFWY1lEV2kiLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMTUyMTA1NTc1NDczMTU1NjUwOCIsImlhdCI6MTc2NzU2MDg2OSwiZXhwIjoxNzY3NTk2ODY5LCJzaWQiOiI0djhVVUgxdXVGYWpyTXlCQ09PckZMU1BrRXB6TXVQcyIsIm5vbmNlIjoiWWtNdFIxVlJTemhJUjNJemJFWXhhVzk0Tnk1TlRVOWxYemd4ZGpOWlMyaGFUbW96VEVnMFlWcG9MUT09In0.dD2zvvaJr4mWznP64aYAuX5MtSNTzeUyF6rOfFc6Lh2IFqniVYRL0diEbDtOSIEh0hyxzAH3vwfz8PzoKyzDe-QObjQcQ_DdRRHMFmVUppNA96z0URXR6r24zdhNVsFmmC7cn9UhE-oYtR2w5N06fB3llykd2kqEGsjmG2rr8ZTOs93Apqnwll996yajYPGnOSJH5xkyjTE0jiOEarQDgh-ZN4H1VzyxlzF_NlbwLwD9JLsq83q9gl5PsrTDEHwqw8k7ENeDHB_scNcLOsu8bvzYG-PN7t5J-J2VrU87ZdAxQ1tQ1Gu-BciKJoLlCcnj2n5LKE9PtuKpQHknljtDxA");
        System.out.println(decoder);
    }
}
